defaults:
  - openmaterial_train_server_disjoint
  - _self_

exp_name: openmaterial_train_server_disjoint_mem
max_img_per_gpu: 20

logging:
  log_dir: /opt/data/private/fyp/vggt_runs/train_disjoint_mem

checkpoint:
  save_dir: /opt/data/private/fyp/vggt_runs/train_disjoint_mem/ckpts

data:
  train:
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_nums: [18, 20]

  val:
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_nums: [18, 20]
