defaults:
  - lora_finetune
  - _self_

exp_name: openmaterial_probe_server
num_workers: 0
max_img_per_gpu: 2
limit_train_batches: 1
limit_val_batches: 0
max_epochs: 1
val_epoch_freq: 1000

logging:
  log_dir: /opt/data/private/fyp/vggt_runs/probe

checkpoint:
  save_dir: /opt/data/private/fyp/vggt_runs/probe/ckpts
  resume_checkpoint_path: /opt/data/private/fyp/vggt/checkpoints/model.pt

data:
  train:
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_nums: [2, 2]
      depth_precompute_dir: /opt/data/private/dataset/OpenMaterial_ablation_depth_cache
      require_precomputed_depth: True
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.openmaterial.OpenMaterialDataset
          split: train
          data_dir: /opt/data/private/dataset/OpenMaterial_ablation
          min_num_images: 8
          len_train: 100000
          load_mask: True
          load_mesh_depth: True

  val:
    num_workers: ${num_workers}
    max_img_per_gpu: ${max_img_per_gpu}
    common_config:
      img_nums: [2, 2]
      depth_precompute_dir: /opt/data/private/dataset/OpenMaterial_ablation_depth_cache
      require_precomputed_depth: True
    dataset:
      _target_: data.composed_dataset.ComposedDataset
      dataset_configs:
        - _target_: data.datasets.openmaterial.OpenMaterialDataset
          split: test
          data_dir: /opt/data/private/dataset/OpenMaterial_ablation
          min_num_images: 8
          len_test: 10000
          load_mask: True
          load_mesh_depth: True
